name: "Build"

on:
  push:
    paths:
      - 'pkg/**'
      - '.golangci.yml'
      - '.releaserc'
      - 'go.*'

jobs:
  test:
    name: Test and Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: -E asasalint,contextcheck,dupl,errchkjson,errname,copyloopvar,gocognit,goconst,gosec,importas,nilnil,promlinter,revive,testpackage,usestdlibvars --timeout 5m

      - name: Test
        run: go test -v ./...

  version:
    name: Create new semantic version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci
        working-directory: packages/only-package-commits

      - name: Create New Version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}